<a href="https://colab.research.google.com/github/avashachhami/Machine-Learning-/blob/main/lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Welcome to Colab!

In [1]:
d = { "a":1,"b":2}

In [2]:
d["a"]

1

In [3]:
d.get("a")

1

In [4]:
d["c"]=3

In [5]:
d["a"]=10

In [6]:
del d["b"]

In [7]:
d.pop("a")

10

In [8]:
d.popitem()

('c', 3)

In [9]:
d.clear()

In [10]:
new_d=d.copy()

In [11]:
d.keys()

dict_keys([])

In [12]:
d.values()

dict_values([])

In [13]:
d.items()

dict_items([])

In [14]:
"a" in d

False

In [15]:
len(d)

0

In [16]:
for k in d:
    pass

In [17]:
for v in d.values():
    pass

In [18]:
for k,v in d.items():
    pass

In [19]:
import pandas as pd

In [20]:
df = pd.DataFrame(columns = [
    {'Name': 'Avash Achhami', 'Age': 20, 'Marks': 88},
    {'Name': 'Preeti Shrestha', 'Age': 19, 'Marks': 98},
    {'Name': 'Songol Chettri', 'Age': 20, 'Marks': 88},
    {'Name': 'Ram hari Krishna', 'Age': 34 , 'Marks':22 },
    {'Name': 'Anurod Kharel', 'Age':21 , 'Marks':100 },
    {'Name': 'Ashim Shretha', 'Age':20 , 'Marks':300 },
    {'Name': 'Subodh Upreti', 'Age':22 , 'Marks':7 },
])

In [24]:
data = [
    {'Name': 'Avash Achhami', 'Age': 20, 'Marks': 88},
    {'Name': 'Preeti Shrestha', 'Age': 19, 'Marks': 98},
    {'Name': 'Songol Chettri', 'Age': 20, 'Marks': 88},
    {'Name': 'Ram hari Krishna', 'Age': 34 , 'Marks':22 },
    {'Name': 'Anurod Kharel', 'Age':21 , 'Marks':100 },
    {'Name': 'Ashim Shretha', 'Age':20 , 'Marks':300 },
    {'Name': 'Subodh Upreti', 'Age':22 , 'Marks':7 },
]

In [25]:
display(df.tail())

               Name  Age  Marks
2    Songol Chettri   20     88
3  Ram hari Krishna   34     22
4     Anurod Kharel   21    100
5     Ashim Shretha   20    300
6     Subodh Upreti   22      7

In [26]:
df.shape

(7, 3)

In [27]:
df.columns

Index(['Name', 'Age', 'Marks'], dtype='object')

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      object
 1   Age     7 non-null      int64
 2   Marks   7 non-null      int64
dtypes: int64(2), object(1)
memory usage: 300.0+ bytes

In [29]:
df.describe()

             Age       Marks
count   7.000000    7.000000
mean   22.285714  100.428571
std     5.250850   95.763349
min    19.000000    7.000000
25%    20.000000   55.000000
50%    20.000000   88.000000
75%    21.500000   99.000000
max    34.000000  300.000000

In [30]:
df['Name']

0       Avash Achhami
1     Preeti Shrestha
2      Songol Chettri
3    Ram hari Krishna
4       Anurod Kharel
5       Ashim Shretha
6       Subodh Upreti
Name: Name, dtype: object

In [31]:
df[['Name','Marks']]

               Name  Marks
0     Avash Achhami     88
1   Preeti Shrestha     98
2    Songol Chettri     88
3  Ram hari Krishna     22
4     Anurod Kharel    100
5     Ashim Shretha    300
6     Subodh Upreti      7

In [32]:
df.iloc[0]

Name     Avash Achhami
Age                 20
Marks               88
Name: 0, dtype: object

In [33]:
df.loc[0,'Marks']

np.int64(88)

In [34]:
df[df['Marks']>90]

              Name  Age  Marks
1  Preeti Shrestha   19     98
4    Anurod Kharel   21    100
5    Ashim Shretha   20    300

In [35]:
df[(df['Marks']>90) & (df['Age']>20)]

            Name  Age  Marks
4  Anurod Kharel   21    100

In [36]:
df['Grade'] = ['A', 'B', 'A', 'C', 'A', 'D', 'B']
display(df)

               Name  Age  Marks Grade
0     Avash Achhami   20     88     A
1   Preeti Shrestha   19     98     B
2    Songol Chettri   20     88     A
3  Ram hari Krishna   34     22     C
4     Anurod Kharel   21    100     A
5     Ashim Shretha   20    300     D
6     Subodh Upreti   22      7     B

In [37]:
df['Marks']=df['Marks']+5
display(df)

               Name  Age  Marks Grade
0     Avash Achhami   20     93     A
1   Preeti Shrestha   19    103     B
2    Songol Chettri   20     93     A
3  Ram hari Krishna   34     27     C
4     Anurod Kharel   21    105     A
5     Ashim Shretha   20    305     D
6     Subodh Upreti   22     12     B

In [38]:
df.loc[df['Name']=='Ram hari Krishna','Marks']=95
display(df)

               Name  Age  Marks Grade
0     Avash Achhami   20     93     A
1   Preeti Shrestha   19    103     B
2    Songol Chettri   20     93     A
3  Ram hari Krishna   34     95     C
4     Anurod Kharel   21    105     A
5     Ashim Shretha   20    305     D
6     Subodh Upreti   22     12     B

In [39]:
df.drop('Age',axis=1)

               Name  Marks Grade
0     Avash Achhami     93     A
1   Preeti Shrestha    103     B
2    Songol Chettri     93     A
3  Ram hari Krishna     95     C
4     Anurod Kharel    105     A
5     Ashim Shretha    305     D
6     Subodh Upreti     12     B

In [40]:
df.sort_values(by='Marks')

               Name  Age  Marks Grade
6     Subodh Upreti   22     12     B
0     Avash Achhami   20     93     A
2    Songol Chettri   20     93     A
3  Ram hari Krishna   34     95     C
1   Preeti Shrestha   19    103     B
4     Anurod Kharel   21    105     A
5     Ashim Shretha   20    305     D

In [41]:
df.sort_values(by='Marks',ascending=False)

               Name  Age  Marks Grade
5     Ashim Shretha   20    305     D
4     Anurod Kharel   21    105     A
1   Preeti Shrestha   19    103     B
3  Ram hari Krishna   34     95     C
0     Avash Achhami   20     93     A
2    Songol Chettri   20     93     A
6     Subodh Upreti   22     12     B

In [42]:
pd.concat([df,df])

               Name  Age  Marks Grade
0     Avash Achhami   20     93     A
1   Preeti Shrestha   19    103     B
2    Songol Chettri   20     93     A
3  Ram hari Krishna   34     95     C
4     Anurod Kharel   21    105     A
5     Ashim Shretha   20    305     D
6     Subodh Upreti   22     12     B
0     Avash Achhami   20     93     A
1   Preeti Shrestha   19    103     B
2    Songol Chettri   20     93     A
3  Ram hari Krishna   34     95     C
4     Anurod Kharel   21    105     A
5     Ashim Shretha   20    305     D
6     Subodh Upreti   22     12     B

In [44]:
pd.read_csv('file.csv')

                         Industry
0              Accounting/Finance
1    Advertising/Public Relations
2              Aerospace/Aviation
3   Arts/Entertainment/Publishing
4                      Automotive
5                Banking/Mortgage
6            Business Development
7            Business Opportunity
8         Clerical/Administrative
9         Construction/Facilities
10                 Consumer Goods
11               Customer Service
12             Education/Training
13               Energy/Utilities
14                    Engineering
15            Government/Military
16                          Green
17                     Healthcare
18             Hospitality/Travel
19                Human Resources
20       Installation/Maintenance
21                      Insurance
22                       Internet
23                Job Search Aids
24       Law Enforcement/Security
25                          Legal
26           Management/Executive
27       Manufacturing/Operations
28                      Marketing
29           Non-Profit/Volunteer
30         Pharmaceutical/Biotech
31          Professional Services
32             QA/Quality Control
33                    Real Estate
34        Restaurant/Food Service
35                         Retail
36                          Sales
37               Science/Research
38                  Skilled Labor
39                     Technology
40             Telecommunications
41       Transportation/Logistics
42                          Other

In [45]:
df.to_csv('file.csv')

In [48]:
pd.read_excel('file.xlsx')

     anurod
0     avash
1  dindayal
2     ashim
3    subodh
4  dikshant
5    jigmet
6    sangat
7    sudeep